[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
asset_manager = "4ZnUCr6vS61XWvbsUQU1giuUZcJfiSZPzy7med9N7PrP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marcelofeitoza/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
