[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_spl_vault = "7MMM9sKJRa1kckgY6esnhvmS5pPBUTF9xMjoUxfHrhHA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
