[package]
name = "scw"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.204"
serde_json = "1.0.120"
solana-client = "2.0.2"
solana-sdk = "2.0.2"
tokio = { version = "1.38.0", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
bs58 = "0.5.1"
